!ArenaConfig
arenas:
  -1: !Arena
    pass_mark: 0.5
    t: 1000
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 38, y: 1, z: 4}
      rotations: [315] #Agent Rotation Parameter
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 7.5, y: .3, z: 17.75} #lower left arm.
      - !Vector3 {x: 17.5, y: .3, z: 33} #top left arm.
      - !Vector3 {x: 23, y: .3, z: 7} #bottom right arm.
      - !Vector3 {x: 32.5, y: .3, z: 22.25} #upper right arm.
      sizes:
      - !Vector3 {x: 1.5, y: 1.5, z: 1.5} #top right arm.
      - !Vector3 {x: .5, y: .5, z: .5} #upper left arm.
      - !Vector3 {x: .5, y: .5, z: .5} #upper right arm.
      - !Vector3 {x: .5, y: .5, z: .5} #lower right arm.
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 20, y: 0, z: 20} #centre base.
      - !Vector3 {x: 20, y: 0, z: 38.75} #top detour path.
      - !Vector3 {x: 38.75, y: 0, z: 20} #right detour path.
      - !Vector3 {x: 1.25, y: 0, z: 20} #left detour path.
      - !Vector3 {x: 9, y: 0, z: 1.25} #bottom detour path.
      - !Vector3 {x: 17.25, y: 0, z: 29} #top left arm.
      - !Vector3 {x: 22.75, y: 0, z: 29} #top right arm.
      - !Vector3 {x: 29, y: 0, z: 22.25} #upper right arm.
      - !Vector3 {x: 29, y: 0, z: 17.75} #lower right arm.
      - !Vector3 {x: 11, y: 0, z: 22.25} #upper left arm.
      - !Vector3 {x: 11, y: 0, z: 17.75} #lower left arm.
      - !Vector3 {x: 17.25, y: 0, z: 7.75} #bottom left arm.
      - !Vector3 {x: 22.75, y: 0, z: 11} #bottom right arm.
      - !Vector3 {x: 16.5, y: .3, z: 24.5} #left barrier on top left arm.
      - !Vector3 {x: 18, y: .3, z: 29} #right barrier on top left arm.
      - !Vector3 {x: 22, y: .3, z: 29} #left barrier on top right arm.
      - !Vector3 {x: 23.5, y: .3, z: 24.5} #right barrier on top right arm.
      - !Vector3 {x: 22, y: .3, z: 11} #left barrier on bottom right arm.
      - !Vector3 {x: 23.5, y: .3, z: 15.5} #right barrier on bottom right arm.
      - !Vector3 {x: 15.25, y: .3, z: 23} #upper barrier on upper left arm.
      - !Vector3 {x: 10.75, y: .3, z: 21.5} #lower barrier on upper left arm.
      - !Vector3 {x: 24.75, y: .3, z: 23} #upper barrier on upper right arm.
      - !Vector3 {x: 29.25, y: .3, z: 21.5} #lower barrier on upper right arm.
      - !Vector3 {x: 10.75, y: .3, z: 18.5} #upper barrier on lower left arm.
      - !Vector3 {x: 15.25, y: .3, z: 17} #lower barrier on lower left arm.
      - !Vector3 {x: 29.25, y: .3, z: 18.5} #upper barrier on lower right arm.
      - !Vector3 {x: 24.75, y: .3, z: 17} #lower barrier on lower right arm.
      - !Vector3 {x: 15.375, y: .3, z: 29} #left occluder on top left arm.
      - !Vector3 {x: 19.125, y: .3, z: 29} #right occluder on top left arm.
      - !Vector3 {x: 20.875, y: .3, z: 29} #left occluder on top right arm.
      - !Vector3 {x: 24.625, y: .3, z: 29} #right occluder on top right arm.
      - !Vector3 {x: 15.375, y: .3, z: 11} #left occluder on bottom left arm.
      - !Vector3 {x: 19.125, y: .3, z: 11} #right occluder on bottom left arm.
      - !Vector3 {x: 20.875, y: .3, z: 11} #left occluder on bottom right arm.
      - !Vector3 {x: 24.625, y: .3, z: 11} #right occluder on bottom right arm.
      - !Vector3 {x: 11, y: .3, z: 24.125} #upper occluder on upper left arm.
      - !Vector3 {x: 11, y: .3, z: 20.375} #lower occluder on upper left arm.
      - !Vector3 {x: 29, y: .3, z: 24.125} #upper occluder on upper right arm.
      - !Vector3 {x: 29, y: .3, z: 20.375} #lower occluder on upper right arm.
      - !Vector3 {x: 11, y: .3, z: 19.625} #upper occluder on lower left arm.
      - !Vector3 {x: 11, y: .3, z: 15.825} #lower occluder on lower left arm.
      - !Vector3 {x: 29, y: .3, z: 19.625} #upper occluder on lower right arm.
      - !Vector3 {x: 29, y: .3, z: 15.825} #lower occluder on lower right arm.
      rotations: [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
      sizes:
      - !Vector3 {x: 9, y: .2, z: 9} #centre base.
      - !Vector3 {x: 35, y: .2, z: 2.5} #top detour path.
      - !Vector3 {x: 2.5, y: .2, z: 40} #right detour path.
      - !Vector3 {x: 2.5, y: .2, z: 40} #left detour path.
      - !Vector3 {x: 13, y: .2, z: 2.5} #bottom detour path.
      - !Vector3 {x: 3.5, y: .2, z: 9} #top left arm.
      - !Vector3 {x: 3.5, y: .2, z: 9} #top right arm.
      - !Vector3 {x: 9, y: .2, z: 3.5} #upper right arm.
      - !Vector3 {x: 9, y: .2, z: 3.5} #lower right arm.
      - !Vector3 {x: 9, y: .2, z: 3.5} #upper left arm.
      - !Vector3 {x: 9, y: .2, z: 3.5} #lower left arm.
      - !Vector3 {x: 3.5, y: .2, z: 15.5} #bottom left arm.
      - !Vector3 {x: 3.5, y: .2, z: 9} #bottom right arm.
      - !Vector3 {x: 2, y: 3, z: .25} #left barrier on top left arm.
      - !Vector3 {x: 2, y: 3, z: .25} #right barrier on top right arm.
      - !Vector3 {x: 2, y: 3, z: .25} #left barrier on top right arm.
      - !Vector3 {x: 2, y: 3, z: .25} #right barrier on top right arm.
      - !Vector3 {x: 2, y: 3, z: .25} #left barrier on bottom right arm.
      - !Vector3 {x: 2, y: 3, z: .25} #right barrier on bottom right arm.
      - !Vector3 {x: .25, y: 3, z: 2} #upper barrier on upper left arm.
      - !Vector3 {x: .25, y: 3, z: 2} #lower barrier on upper left arm.
      - !Vector3 {x: .25, y: 3, z: 2} #upper barrier on upper right arm
      - !Vector3 {x: .25, y: 3, z: 2} #lower barrier on upper right arm.
      - !Vector3 {x: .25, y: 3, z: 2} #upper barrier on lower left arm.
      - !Vector3 {x: .25, y: 3, z: 2} #lower barrier on lower left arm.
      - !Vector3 {x: .25, y: 3, z: 2} #upper barrier on lower right arm.
      - !Vector3 {x: .25, y: 3, z: 2} #lower barrier on lower right arm.
      - !Vector3 {x: .25, y: 3, z: 9} #left occluder on top left arm.
      - !Vector3 {x: .25, y: 3, z: 9} #right occluder on top left arm.
      - !Vector3 {x: .25, y: 3, z: 9} #left occluder on top right arm.
      - !Vector3 {x: .25, y: 3, z: 9} #right occluder on top right arm.
      - !Vector3 {x: .25, y: 3, z: 9} #left occluder on bottom left arm.
      - !Vector3 {x: .25, y: 3, z: 9} #right occluder on botton left arm.
      - !Vector3 {x: .25, y: 3, z: 9} #left occluder on bottom right arm.
      - !Vector3 {x: .25, y: 3, z: 9} #right occluder on bottom right arm.
      - !Vector3 {x: 9, y: 3, z: .25} #upper occluder on upper left arm.
      - !Vector3 {x: 9, y: 3, z: .25} #lower occluder on upper left arm.
      - !Vector3 {x: 9, y: 3, z: .25} #upper occluder on upper right arm.
      - !Vector3 {x: 9, y: 3, z: .25} #lower occluder on upper right arm.
      - !Vector3 {x: 9, y: 3, z: .25} #upper occluder on lower left arm.
      - !Vector3 {x: 9, y: 3, z: .25} #lower occluder on lower left arm.
      - !Vector3 {x: 9, y: 3, z: .25} #upper occluder on lower right arm.
      - !Vector3 {x: 9, y: 3, z: .25} #lower occluder on lower right arm.
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
    - !Item
      name: WallTransparent
      positions:
      - !Vector3 {x: 20, y: 0, z: 37.4} #top detour barrier.
      - !Vector3 {x: 37.4, y: 0, z: 18.8} #right detour barrier.
      - !Vector3 {x: 2.6, y: 0, z: 20} #left detour barrier.
      - !Vector3 {x: 9, y: 0, z: 2.6} #bottom detour barrier.
      - !Vector3 {x: 15.4, y: 0, z: 4.5625} #left barrier on lower left arm.
      - !Vector3 {x: 19.1, y: 0, z: 3.3} #right barrier on lower right arm.
      rotations: [0,0,0,0,0,0]
      sizes:
      - !Vector3 {x: 35, y: 1, z: .2} #top detour barrier.
      - !Vector3 {x: .2, y: 1, z: 37} #right detour barrier.
      - !Vector3 {x: .2, y: 1, z: 34.5} #left detour barrier.
      - !Vector3 {x: 13, y: 1, z: .2} #bottom detour barrier.
      - !Vector3 {x: .2, y: 1, z: 3.7} #left barrier on lower left arm.
      - !Vector3 {x: .2, y: 1, z: 6.25} #right barrier on lower right arm.
    - !Item
      name: DeathZone
      positions:
      - !Vector3 {x: 20, y: 0, z: 20}
      rotations: [0]
      sizes:
      - !Vector3 {x: 40, y: 0, z: 40}
