!ArenaConfig
arenas:
  -1: !Arena
    pass_mark: 2.5
    t: 400
    items:
      - !Item
        name: Agent
        positions:
        - !Vector3 {x: 20, y: 2, z: 1}
        rotations: [0]
        frozenAgentDelays: [8]
      - !Item
        name: Wall
        positions:
        - !Vector3 {x: 20, y: 0, z: 9.5}
        - !Vector3 {x: 25, y: 0, z: 19.25}
        sizes:
        - !Vector3 {x: 2, y: 0.7, z: 19}
        - !Vector3 {x: 30, y: 0.7, z: 0.5}
        colors:
        - !RGB {r: 0, g: 0, b: 255}
        - !RGB {r: 248, g: 253, b: 212}
        rotations: [0,0]
      - !Item
        name: Wall
        positions:
        - !Vector3 {x: 12.5, y: 0.7, z: 19.25}
        - !Vector3 {x: 18.5, y: 0.7, z: 19.25}
        - !Vector3 {x: 24.5, y: 0.7, z: 19.25}
        - !Vector3 {x: 30.5, y: 0.7, z: 19.25}
        - !Vector3 {x: 36.5, y: 0.7, z: 19.25}
        sizes:
        - !Vector3 {x: 5, y: 0.5, z: 0.5}
        - !Vector3 {x: 5, y: 0.5, z: 0.5}
        - !Vector3 {x: 5, y: 0.5, z: 0.5}
        - !Vector3 {x: 5, y: 0.5, z: 0.5}
        - !Vector3 {x: 5, y: 0.5, z: 0.5}
        colors:
        - !RGB {r: 248, g: 253, b: 212}
        - !RGB {r: 248, g: 253, b: 212}
        - !RGB {r: 248, g: 253, b: 212}
        - !RGB {r: 248, g: 253, b: 212}
        - !RGB {r: 248, g: 253, b: 212}
        rotations: [0,0,0,0,0]
      - !Item
        name: Wall
        positions:
        - !Vector3 {x: 14.25, y: 1.3, z: 19.25}
        - !Vector3 {x: 22, y: 1.3, z: 19.25}
        - !Vector3 {x: 28, y: 1.3, z: 19.25}
        - !Vector3 {x: 35.75, y: 1.3, z: 19.25}
        sizes:
        - !Vector3 {x: 8.5, y: 0.5, z: 0.5}
        - !Vector3 {x: 5, y: 0.5, z: 0.5}
        - !Vector3 {x: 5, y: 0.5, z: 0.5}
        - !Vector3 {x: 8.5, y: 0.5, z: 0.5}
        colors:
        - !RGB {r: 248, g: 253, b: 212}
        - !RGB {r: 248, g: 253, b: 212}
        - !RGB {r: 248, g: 253, b: 212}
        - !RGB {r: 248, g: 253, b: 212}
        rotations: [0,0,0,0]
      - !Item
        name: Wall
        positions:
        - !Vector3 {x: 12.5, y: 1.8, z: 19.25}
        - !Vector3 {x: 18.5, y: 1.8, z: 19.25}
        - !Vector3 {x: 24.5, y: 1.8, z: 19.25}
        - !Vector3 {x: 30.5, y: 1.8, z: 19.25}
        - !Vector3 {x: 36.5, y: 1.8, z: 19.25}
        sizes:
        - !Vector3 {x: 5, y: 0.5, z: 0.5}
        - !Vector3 {x: 5, y: 0.5, z: 0.5}
        - !Vector3 {x: 5, y: 0.5, z: 0.5}
        - !Vector3 {x: 5, y: 0.5, z: 0.5}
        - !Vector3 {x: 5, y: 0.5, z: 0.5}
        colors:
        - !RGB {r: 248, g: 253, b: 212}
        - !RGB {r: 248, g: 253, b: 212}
        - !RGB {r: 248, g: 253, b: 212}
        - !RGB {r: 248, g: 253, b: 212}
        - !RGB {r: 248, g: 253, b: 212}
        rotations: [0,0,0,0,0]
      - !Item
        name: Wall
        positions:
        - !Vector3 {x: 14.25, y: 2.3, z: 19.25}
        - !Vector3 {x: 22, y: 2.3, z: 19.25}
        - !Vector3 {x: 28, y: 2.3, z: 19.25}
        - !Vector3 {x: 36.75, y: 2.3, z: 19.25}
        sizes:
        - !Vector3 {x: 8.5, y: 0.5, z: 0.5}
        - !Vector3 {x: 5, y: 0.5, z: 0.5}
        - !Vector3 {x: 5, y: 0.5, z: 0.5}
        - !Vector3 {x: 8.5, y: 0.5, z: 0.5}
        colors:
        - !RGB {r: 248, g: 253, b: 212}
        - !RGB {r: 248, g: 253, b: 212}
        - !RGB {r: 248, g: 253, b: 212}
        - !RGB {r: 248, g: 253, b: 212}
        rotations: [0,0,0,0]
      - !Item
        name: Wall
        positions:
        - !Vector3 {x: 12.5, y: 2.8, z: 19.25}
        - !Vector3 {x: 18.5, y: 2.8, z: 19.25}
        - !Vector3 {x: 24.5, y: 2.8, z: 19.25}
        - !Vector3 {x: 30.5, y: 2.8, z: 19.25}
        - !Vector3 {x: 36.5, y: 2.8, z: 19.25}
        sizes:
        - !Vector3 {x: 5, y: 0.5, z: 0.5}
        - !Vector3 {x: 5, y: 0.5, z: 0.5}
        - !Vector3 {x: 5, y: 0.5, z: 0.5}
        - !Vector3 {x: 5, y: 0.5, z: 0.5}
        - !Vector3 {x: 5, y: 0.5, z: 0.5}
        colors:
        - !RGB {r: 248, g: 253, b: 212}
        - !RGB {r: 248, g: 253, b: 212}
        - !RGB {r: 248, g: 253, b: 212}
        - !RGB {r: 248, g: 253, b: 212}
        - !RGB {r: 248, g: 253, b: 212}
        rotations: [0,0,0,0,0]
      - !Item
        name: Wall
        positions:
        - !Vector3 {x: 14.25, y: 3.3, z: 19.25}
        - !Vector3 {x: 22, y: 3.3, z: 19.25}
        - !Vector3 {x: 28, y: 3.3, z: 19.25}
        - !Vector3 {x: 25.75, y: 3.3, z: 19.25}
        sizes:
        - !Vector3 {x: 8.5, y: 0.5, z: 0.5}
        - !Vector3 {x: 5, y: 0.5, z: 0.5}
        - !Vector3 {x: 5, y: 0.5, z: 0.5}
        - !Vector3 {x: 8.5, y: 0.5, z: 0.5}
        colors:
        - !RGB {r: 248, g: 253, b: 212}
        - !RGB {r: 248, g: 253, b: 212}
        - !RGB {r: 248, g: 253, b: 212}
        - !RGB {r: 248, g: 253, b: 212}
        rotations: [0,0,0,0]
      - !Item
        name: Ramp
        positions:
        - !Vector3 {x: 15, y: 0, z: 30}
        - !Vector3 {x: 38, y: 0, z: 30}
        sizes:
        - !Vector3 {x: 17, y: 1, z: 4}
        - !Vector3 {x: 17, y: 1, z: 4}
        rotations: [270, 270]
        colors:
        - !RGB {r: 255, g: 0, b: 255}
        - !RGB {r: 255, g: 0, b: 255}
      - !Item #GoodGoalBounce
        name: GoodGoalBounce #GoodGoalBounce
        positions: #GoodGoalBounce
        - !Vector3 {x: 2, y: 0, z: 23.5} #GoodGoalBounce
        sizes: #GoodGoalBounce
        - !Vector3 {x: 3, y: 3, z: 3} #GoodGoalBounce
        rotations: [90] #GoodGoalBounce
