!ArenaConfig
arenas:
  -1: !Arena
    pass_mark: 2
    t: 400
    items:
      - !Item
        name: Agent
        positions:
        - !Vector3 {x: 20, y: 2, z: 1}
        rotations: [0]
        frozenAgentDelays: [8]
      - !Item
        name: Wall
        positions:
        - !Vector3 {x: 20, y: 0, z: 9.5}
        - !Vector3 {x: 28.5, y: 0, z: 20.5}
        - !Vector3 {x: 17.5, y: 0.25, z: 20.5}
        - !Vector3 {x: 19.5, y: 0.25, z: 20.5}
        - !Vector3 {x: 21.5, y: 0.25, z: 20.5}
        - !Vector3 {x: 23.5, y: 0.25, z: 20.5}
        - !Vector3 {x: 25.5, y: 0.25, z: 20.5}
        - !Vector3 {x: 27.5, y: 0.25, z: 20.5}
        - !Vector3 {x: 29.5, y: 0.25, z: 20.5}
        - !Vector3 {x: 31.5, y: 0.25, z: 20.5}
        - !Vector3 {x: 33.5, y: 0.25, z: 20.5}
        - !Vector3 {x: 35.5, y: 0.25, z: 20.5}
        - !Vector3 {x: 37.5, y: 0.25, z: 20.5}
        - !Vector3 {x: 39.5, y: 0.25, z: 20.5}
        sizes:
        - !Vector3 {x: 2, y: 0.7, z: 19}
        - !Vector3 {x: 23, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        colors:
        - !RGB {r: 0, g: 0, b: 255}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        rotations: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
      - !Item
        name: Wall
        positions:
        - !Vector3 {x: 28.5, y: 0.5, z: 20.5}
        - !Vector3 {x: 18.5, y: 0.75, z: 20.5}
        - !Vector3 {x: 20.5, y: 0.75, z: 20.5}
        - !Vector3 {x: 22.5, y: 0.75, z: 20.5}
        - !Vector3 {x: 24.5, y: 0.75, z: 20.5}
        - !Vector3 {x: 26.5, y: 0.75, z: 20.5}
        - !Vector3 {x: 28.5, y: 0.75, z: 20.5}
        - !Vector3 {x: 30.5, y: 0.75, z: 20.5}
        - !Vector3 {x: 32.5, y: 0.75, z: 20.5}
        - !Vector3 {x: 34.5, y: 0.75, z: 20.5}
        - !Vector3 {x: 36.5, y: 0.75, z: 20.5}
        - !Vector3 {x: 38.5, y: 0.75, z: 20.5}
        sizes:
        - !Vector3 {x: 23, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        colors:
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        rotations: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
      - !Item
        name: Wall
        positions:
        - !Vector3 {x: 28.5, y: 1, z: 20.5}
        - !Vector3 {x: 17.5, y: 1.25, z: 20.5}
        - !Vector3 {x: 19.5, y: 1.25, z: 20.5}
        - !Vector3 {x: 21.5, y: 1.25, z: 20.5}
        - !Vector3 {x: 23.5, y: 1.25, z: 20.5}
        - !Vector3 {x: 25.5, y: 1.25, z: 20.5}
        - !Vector3 {x: 27.5, y: 1.25, z: 20.5}
        - !Vector3 {x: 29.5, y: 1.25, z: 20.5}
        - !Vector3 {x: 31.5, y: 1.25, z: 20.5}
        - !Vector3 {x: 33.5, y: 1.25, z: 20.5}
        - !Vector3 {x: 35.5, y: 1.25, z: 20.5}
        - !Vector3 {x: 37.5, y: 1.25, z: 20.5}
        - !Vector3 {x: 39.5, y: 1.25, z: 20.5}
        sizes:
        - !Vector3 {x: 23, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        colors:
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        rotations: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
      - !Item
        name: Wall
        positions:
        - !Vector3 {x: 28.5, y: 1.5, z: 20.5}
        - !Vector3 {x: 18.5, y: 1.75, z: 20.5}
        - !Vector3 {x: 20.5, y: 1.75, z: 20.5}
        - !Vector3 {x: 22.5, y: 1.75, z: 20.5}
        - !Vector3 {x: 24.5, y: 1.75, z: 20.5}
        - !Vector3 {x: 26.5, y: 1.75, z: 20.5}
        - !Vector3 {x: 28.5, y: 1.75, z: 20.5}
        - !Vector3 {x: 30.5, y: 1.75, z: 20.5}
        - !Vector3 {x: 32.5, y: 1.75, z: 20.5}
        - !Vector3 {x: 34.5, y: 1.75, z: 20.5}
        - !Vector3 {x: 36.5, y: 1.75, z: 20.5}
        - !Vector3 {x: 38.5, y: 1.75, z: 20.5}
        sizes:
        - !Vector3 {x: 23, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        colors:
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        rotations: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
      - !Item
        name: Wall
        positions:
        - !Vector3 {x: 28.5, y: 2, z: 20.5}
        - !Vector3 {x: 17.5, y: 2.25, z: 20.5}
        - !Vector3 {x: 19.5, y: 2.25, z: 20.5}
        - !Vector3 {x: 21.5, y: 2.25, z: 20.5}
        - !Vector3 {x: 23.5, y: 2.25, z: 20.5}
        - !Vector3 {x: 25.5, y: 2.25, z: 20.5}
        - !Vector3 {x: 27.5, y: 2.25, z: 20.5}
        - !Vector3 {x: 29.5, y: 2.25, z: 20.5}
        - !Vector3 {x: 31.5, y: 2.25, z: 20.5}
        - !Vector3 {x: 33.5, y: 2.25, z: 20.5}
        - !Vector3 {x: 35.5, y: 2.25, z: 20.5}
        - !Vector3 {x: 37.5, y: 2.25, z: 20.5}
        - !Vector3 {x: 39.5, y: 2.25, z: 20.5}
        sizes:
        - !Vector3 {x: 23, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        colors:
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        rotations: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
      - !Item
        name: Wall
        positions:
        - !Vector3 {x: 28.5, y: 2.5, z: 20.5}
        - !Vector3 {x: 18.5, y: 2.75, z: 20.5}
        - !Vector3 {x: 20.5, y: 2.75, z: 20.5}
        - !Vector3 {x: 22.5, y: 2.75, z: 20.5}
        - !Vector3 {x: 24.5, y: 2.75, z: 20.5}
        - !Vector3 {x: 26.5, y: 2.75, z: 20.5}
        - !Vector3 {x: 28.5, y: 2.75, z: 20.5}
        - !Vector3 {x: 30.5, y: 2.75, z: 20.5}
        - !Vector3 {x: 32.5, y: 2.75, z: 20.5}
        - !Vector3 {x: 34.5, y: 2.75, z: 20.5}
        - !Vector3 {x: 36.5, y: 2.75, z: 20.5}
        - !Vector3 {x: 38.5, y: 2.75, z: 20.5}
        sizes:
        - !Vector3 {x: 23, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        colors:
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        rotations: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
      - !Item
        name: Wall
        positions:
        - !Vector3 {x: 28.5, y: 3, z: 20.5}
        - !Vector3 {x: 17.5, y: 3.25, z: 20.5}
        - !Vector3 {x: 19.5, y: 3.25, z: 20.5}
        - !Vector3 {x: 21.5, y: 3.25, z: 20.5}
        - !Vector3 {x: 23.5, y: 3.25, z: 20.5}
        - !Vector3 {x: 25.5, y: 3.25, z: 20.5}
        - !Vector3 {x: 27.5, y: 3.25, z: 20.5}
        - !Vector3 {x: 29.5, y: 3.25, z: 20.5}
        - !Vector3 {x: 31.5, y: 3.25, z: 20.5}
        - !Vector3 {x: 33.5, y: 3.25, z: 20.5}
        - !Vector3 {x: 35.5, y: 3.25, z: 20.5}
        - !Vector3 {x: 37.5, y: 3.25, z: 20.5}
        - !Vector3 {x: 39.5, y: 3.25, z: 20.5}
        sizes:
        - !Vector3 {x: 23, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        colors:
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
        rotations: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
      - !Item
        name: Ramp
        positions:
        - !Vector3 {x: 15, y: 0, z: 30}
        - !Vector3 {x: 38, y: 0, z: 30}
        sizes:
        - !Vector3 {x: 17, y: 1, z: 4}
        - !Vector3 {x: 17, y: 1, z: 4}
        rotations: [270, 270]
        colors:
        - !RGB {r: 255, g: 0, b: 255}
        - !RGB {r: 255, g: 0, b: 255}
      - !Item #GoodGoalBounce
        name: GoodGoalBounce #GoodGoalBounce
        positions: #GoodGoalBounce
        - !Vector3 {x: 2, y: 0, z: 23.5} #GoodGoalBounce
        sizes: #GoodGoalBounce
        - !Vector3 {x: 3, y: 3, z: 3} #GoodGoalBounce
        rotations: [90] #GoodGoalBounce
      - !Item #decoy
        name: GoodGoal #decoy
        positions: #decoy
        - !Vector3 {x: 30, y: 0, z: 10} #decoy
        sizes: #decoy
        - !Vector3 {x: 1, y: 1, z: 1} #decoy
        rotations: [0] #decoy
