!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2
    t: 400
    items:
      - !Item
        name: Agent
        positions:
        - !Vector3 {x: 20, y: 2, z: 1}
        rotations: [0]
        frozenAgentDelays: [8]
      - !Item
        name: Wall
        positions:
        - !Vector3 {x: 20, y: 0, z: 7}
        - !Vector3 {x: 11.5, y: 0, z: 15.5}
        - !Vector3 {x: 22.5, y: 0.25, z: 15.5}
        - !Vector3 {x: 20.5, y: 0.25, z: 15.5}
        - !Vector3 {x: 18.5, y: 0.25, z: 15.5}
        - !Vector3 {x: 16.5, y: 0.25, z: 15.5}
        - !Vector3 {x: 14.5, y: 0.25, z: 15.5}
        - !Vector3 {x: 12.5, y: 0.25, z: 15.5}
        - !Vector3 {x: 10.5, y: 0.25, z: 15.5}
        - !Vector3 {x: 8.5, y: 0.25, z: 15.5}
        - !Vector3 {x: 6.5, y: 0.25, z: 15.5}
        - !Vector3 {x: 4.5, y: 0.25, z: 15.5}
        - !Vector3 {x: 2.5, y: 0.25, z: 15.5}
        - !Vector3 {x: 0.5, y: 0.25, z: 15.5}
        sizes:
        - !Vector3 {x: 2, y: 0.7, z: 14}
        - !Vector3 {x: 23, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        colors:
        - !RGB {r: 0, g: 0, b: 255}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        rotations: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
      - !Item
        name: Wall
        positions:
        - !Vector3 {x: 11.5, y: 0.5, z: 15.5}
        - !Vector3 {x: 21.5, y: 0.75, z: 15.5}
        - !Vector3 {x: 19.5, y: 0.75, z: 15.5}
        - !Vector3 {x: 17.5, y: 0.75, z: 15.5}
        - !Vector3 {x: 15.5, y: 0.75, z: 15.5}
        - !Vector3 {x: 13.5, y: 0.75, z: 15.5}
        - !Vector3 {x: 11.5, y: 0.75, z: 15.5}
        - !Vector3 {x: 9.5, y: 0.75, z: 15.5}
        - !Vector3 {x: 7.5, y: 0.75, z: 15.5}
        - !Vector3 {x: 5.5, y: 0.75, z: 15.5}
        - !Vector3 {x: 3.5, y: 0.75, z: 15.5}
        - !Vector3 {x: 1.5, y: 0.75, z: 15.5}
        sizes:
        - !Vector3 {x: 23, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        colors:
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        rotations: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
      - !Item
        name: Wall
        positions:
        - !Vector3 {x: 11.5, y: 1, z: 15.5}
        - !Vector3 {x: 22.5, y: 1.25, z: 15.5}
        - !Vector3 {x: 20.5, y: 1.25, z: 15.5}
        - !Vector3 {x: 18.5, y: 1.25, z: 15.5}
        - !Vector3 {x: 16.5, y: 1.25, z: 15.5}
        - !Vector3 {x: 14.5, y: 1.25, z: 15.5}
        - !Vector3 {x: 12.5, y: 1.25, z: 15.5}
        - !Vector3 {x: 10.5, y: 1.25, z: 15.5}
        - !Vector3 {x: 8.5, y: 1.25, z: 15.5}
        - !Vector3 {x: 6.5, y: 1.25, z: 15.5}
        - !Vector3 {x: 4.5, y: 1.25, z: 15.5}
        - !Vector3 {x: 2.5, y: 1.25, z: 15.5}
        - !Vector3 {x: 0.5, y: 1.25, z: 15.5}
        sizes:
        - !Vector3 {x: 23, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        colors:
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        rotations: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
      - !Item
        name: Wall
        positions:
        - !Vector3 {x: 11.5, y: 1.5, z: 15.5}
        - !Vector3 {x: 21.5, y: 1.75, z: 15.5}
        - !Vector3 {x: 19.5, y: 1.75, z: 15.5}
        - !Vector3 {x: 17.5, y: 1.75, z: 15.5}
        - !Vector3 {x: 15.5, y: 1.75, z: 15.5}
        - !Vector3 {x: 13.5, y: 1.75, z: 15.5}
        - !Vector3 {x: 11.5, y: 1.75, z: 15.5}
        - !Vector3 {x: 9.5, y: 1.75, z: 15.5}
        - !Vector3 {x: 7.5, y: 1.75, z: 15.5}
        - !Vector3 {x: 5.5, y: 1.75, z: 15.5}
        - !Vector3 {x: 3.5, y: 1.75, z: 15.5}
        - !Vector3 {x: 1.5, y: 1.75, z: 15.5}
        sizes:
        - !Vector3 {x: 23, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        colors:
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        rotations: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
      - !Item
        name: Wall
        positions:
        - !Vector3 {x: 11.5, y: 2, z: 15.5}
        - !Vector3 {x: 22.5, y: 2.25, z: 15.5}
        - !Vector3 {x: 20.5, y: 2.25, z: 15.5}
        - !Vector3 {x: 18.5, y: 2.25, z: 15.5}
        - !Vector3 {x: 16.5, y: 2.25, z: 15.5}
        - !Vector3 {x: 14.5, y: 2.25, z: 15.5}
        - !Vector3 {x: 12.5, y: 2.25, z: 15.5}
        - !Vector3 {x: 10.5, y: 2.25, z: 15.5}
        - !Vector3 {x: 8.5, y: 2.25, z: 15.5}
        - !Vector3 {x: 6.5, y: 2.25, z: 15.5}
        - !Vector3 {x: 4.5, y: 2.25, z: 15.5}
        - !Vector3 {x: 2.5, y: 2.25, z: 15.5}
        - !Vector3 {x: 0.5, y: 2.25, z: 15.5}
        sizes:
        - !Vector3 {x: 23, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        colors:
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        rotations: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
      - !Item
        name: Wall
        positions:
        - !Vector3 {x: 11.5, y: 2.5, z: 15.5}
        - !Vector3 {x: 21.5, y: 2.75, z: 15.5}
        - !Vector3 {x: 19.5, y: 2.75, z: 15.5}
        - !Vector3 {x: 17.5, y: 2.75, z: 15.5}
        - !Vector3 {x: 15.5, y: 2.75, z: 15.5}
        - !Vector3 {x: 13.5, y: 2.75, z: 15.5}
        - !Vector3 {x: 11.5, y: 2.75, z: 15.5}
        - !Vector3 {x: 9.5, y: 2.75, z: 15.5}
        - !Vector3 {x: 7.5, y: 2.75, z: 15.5}
        - !Vector3 {x: 5.5, y: 2.75, z: 15.5}
        - !Vector3 {x: 3.5, y: 2.75, z: 15.5}
        - !Vector3 {x: 1.5, y: 2.75, z: 15.5}
        sizes:
        - !Vector3 {x: 23, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        colors:
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        rotations: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
      - !Item
        name: Wall
        positions:
        - !Vector3 {x: 11.5, y: 3, z: 15.5}
        - !Vector3 {x: 22.5, y: 3.25, z: 15.5}
        - !Vector3 {x: 20.5, y: 3.25, z: 15.5}
        - !Vector3 {x: 18.5, y: 3.25, z: 15.5}
        - !Vector3 {x: 16.5, y: 3.25, z: 15.5}
        - !Vector3 {x: 14.5, y: 3.25, z: 15.5}
        - !Vector3 {x: 12.5, y: 3.25, z: 15.5}
        - !Vector3 {x: 10.5, y: 3.25, z: 15.5}
        - !Vector3 {x: 8.5, y: 3.25, z: 15.5}
        - !Vector3 {x: 6.5, y: 3.25, z: 15.5}
        - !Vector3 {x: 4.5, y: 3.25, z: 15.5}
        - !Vector3 {x: 2.5, y: 3.25, z: 15.5}
        - !Vector3 {x: 0.5, y: 3.25, z: 15.5}
        sizes:
        - !Vector3 {x: 23, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        - !Vector3 {x: 1, y: 0.25, z: 1.5}
        colors:
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        rotations: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
      - !Item
        name: Ramp
        positions:
        - !Vector3 {x: 25, y: 0, z: 27.5}
        - !Vector3 {x: 2, y: 0, z: 27.5}
        sizes:
        - !Vector3 {x: 22, y: 1, z: 4}
        - !Vector3 {x: 22, y: 1, z: 4}
        rotations: [90, 90]
        colors:
        - !RGB {r: 255, g: 0, b: 255}
        - !RGB {r: 255, g: 0, b: 255}
      - !Item #GoodGoalBounce
        name: GoodGoalBounce #GoodGoalBounce
        positions: #GoodGoalBounce
        - !Vector3 {x: 38, y: 0, z: 18.5} #GoodGoalBounce
        sizes: #GoodGoalBounce
        - !Vector3 {x: 3, y: 3, z: 3} #GoodGoalBounce
        rotations: [270] #GoodGoalBounce
      - !Item #decoy
        name: GoodGoal #decoy
        positions: #decoy
        - !Vector3 {x: 10, y: 0, z: 10} #decoy
        sizes: #decoy
        - !Vector3 {x: 2.5, y: 2.5, z: 2.5} #decoy size
        rotations: [0] #decoy
