!ArenaConfig
arenas:
  -1: !Arena
    pass_mark: 2
    t: 500
    items:
    - !Item
      name: WallTransparent
      positions:
      - !Vector3 {x: 20, y: 0, z: 20}
      - !Vector3 {x: 17, y: 0, z: 12.78}
      - !Vector3 {x: 23, y: 0, z: 27.22}
      rotations: [70, 110, 110]
      sizes:
      - !Vector3 {x: 27.5, y: 10, z: 1}
      - !Vector3 {x: 13, y: 10, z: 1}
      - !Vector3 {x: 13, y: 10, z: 1}
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 20, y: 0, z: 27.4}
      sizes:
      - !Vector3 {x: 1.5, y: 1.5, z: 1.5} #Goal Size
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 22, y: 0, z: 20}
      rotations: [-1] #Agent Rotation Parameter
      skins:
      - "hedgehog"
