!ArenaConfig
arenas:
  0: !Arena
    pass_mark: -0.5
    t: 500
    items:
    - !Item
      name: WallTransparent
      positions:
      - !Vector3 {x: 15, y: 0, z: 25}
      - !Vector3 {x: 25, y: 0, z: 25}
      - !Vector3 {x: 15, y: 0, z: 15}
      - !Vector3 {x: 25, y: 0, z: 15}
      rotations: [45, 135, 135, 45]
      sizes:
      - !Vector3 {x: 13, y: 10, z: 1}
      - !Vector3 {x: 13, y: 10, z: 1}
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 20, y: 0, z: 24}
      sizes:
      - !Vector3 {x: 0.5, y: 0.5, z: 0.5} #Goal Size
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 18}
      rotations: [180] #Agent Rotation Parameter
      skins:
      - "hedgehog"
