!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 3
    t: 500
    items:
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 20, y: 0, z: 20}
      - !Vector3 {x: 20, y: 3.1, z: 20}
      - !Vector3 {x: 13.75, y: 0, z: 10}
      - !Vector3 {x: 26.25, y: 0, z: 10}
      - !Vector3 {x: 30, y: 0, z: 20}
      - !Vector3 {x: 15.25, y: .1, z: 16.25}
      - !Vector3 {x: 15.25, y: .1, z: 23.75}
      - !Vector3 {x: 10, y: 0, z: 20}
      - !Vector3 {x: 24.75, y: .1, z: 20}
      rotations: [0,0,0,0,0,0,0,0,0]
      sizes:
      - !Vector3 {x: 10, y: 0.1, z: 10}
      - !Vector3 {x: 10, y: 0.1, z: 10}
      - !Vector3 {x: 7.5, y: 3, z: 1}
      - !Vector3 {x: 7.5, y: 3, z: 1}
      - !Vector3 {x: 1, y: 3, z: 19}
      - !Vector3 {x: 0.5, y: 3, z: 2.5}
      - !Vector3 {x: 0.5, y: 3, z: 2.5}
      - !Vector3 {x: 1, y: 3, z: 19}
      - !Vector3 {x: .5, y: 3, z: 9}
      colors:
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
    - !Item
      name: WallTransparent
      positions:
      - !Vector3 {x: 20, y: .1, z: 24.75}
      - !Vector3 {x: 20, y: 0, z: 30}
      - !Vector3 {x: 20, y: 0, z: 10}
      - !Vector3 {x: 20, y: .1, z: 15.25}
      rotations: [0,0,0,0]
      sizes:
      - !Vector3 {x: 9, y: 3, z: 0.5}
      - !Vector3 {x: 19, y: 3, z: 1}
      - !Vector3 {x: 19, y: 3, z: 1}
      - !Vector3 {x: 9, y: 3, z: .5}
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 20, y: 0, z: 37}
      sizes:
      - !Vector3 {x: 4, y: 4, z: 4}
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: .1, z: 20}
      rotations: [0]
