!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 1 #powershelled pass_mark
    t: 750 #time limit
    items:
      - !Item #agent item parameter
        name: Agent #agent name
        positions: #agent position parameter
        - !Vector3 {x: 20, y: 2, z: 1} #agent position
        rotations: [0] #agent rotation
      - !Item #wall item parameter
        name: Wall  #wall name
        positions:  #wall position parameter
        - !Vector3 {x: 20, y: 0, z: 10} #wall position
        sizes: #wall size parameter
        - !Vector3 {x: 2, y: 0.7, z: 20} #wall size
        colors: #wall color parameter
        - !RGB {r: 0, g: 0, b: 255} #wall color
        rotations: [0] #wall rotations
      - !Item #GoodGoalBounce item parameter
        name: GoodGoalBounce #GoodGoalBounce name
        positions: #GoodGoalBounce position parameter
        - !Vector3 {x: 38, y: 1, z: 32} #GoodGoalBounce position
        sizes: #GoodGoalBounce size parameter
        - !Vector3 {x: 2, y: 2, z: 2} #GoodGoalBounce Size
        rotations: [270] #GoodGoalBounce rotation
      - !Item #death zone item parameter
        name: DeathZone #death zone name
        positions: #death zone position parameter
        - !Vector3 {x: 11, y: 0, z: 24} #death zone position
        sizes: #death zone size parameter
        - !Vector3 {x: 22, y: 0, z: 8} #death zone size
        rotations: [0] #death zone rotation







