!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0.5
    t: 500
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 39, y: 0, z: 1}
      rotations: [330] #Agent Rotation Parameter
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 10, y: 0, z: 25}
      - !Vector3 {x: 20, y: 0, z: 30}
      - !Vector3 {x: 30, y: 0, z: 25}
      - !Vector3 {x: 20, y: 0, z: 20}
      rotations: [0,0,0,0]
      colors:
      - !RGB {r: 0, g: 0, b: 255}
      - !RGB {r: 0, g: 0, b: 255}
      - !RGB {r: 0, g: 0, b: 255}
      - !RGB {r: 102, g: 51, b: 1} #color parameter
      sizes:
      - !Vector3 {x: 4, y: 1, z: 15}
      - !Vector3 {x: 16, y: 1, z: 2}
      - !Vector3 {x: 4, y: 1, z: 15}
      - !Vector3 {x: 2, y: 4, z: 12}
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 30, y: 1, z: 20}
      sizes:
      - !Vector3 {x: 1.5, y: 1.5, z: 1.5} #Goal Size
    - !Item
      name: Ramp
      positions:
      - !Vector3 {x: 10, y: 0, z: 15}
      rotations: [180]
      sizes:
      - !Vector3 {x: 4, y: 1, z: 5}
      colors:
      - !RGB {r: 255, g: 0, b: 255}
