!ArenaConfig
arenas:
  -1: !Arena

    pass_mark: 1
    t: 500
    items:
      - !Item
        name: Agent
        positions:
        - !Vector3 {x: 20, y: 3, z: 9}
        rotations: [0]
        frozenAgentDelays: [12]
      - !Item
        name: Wall
        positions:
        - !Vector3 {x: 20, y: 0, z: 5}
        - !Vector3 {x: 25, y: 0, z: 30}
        - !Vector3 {x: 15, y: 0, z: 30}
        sizes:
        - !Vector3 {x: 10, y: 2, z: 10}
        - !Vector3 {x: 5.5, y: 11, z: 2}
        - !Vector3 {x: 5.5, y: 11, z: 2}
        colors:
        - !RGB {r: 0, g: 0, b: 255}
        - !RGB {r: -1, g: -1, b: -1}
        - !RGB {r: -1, g: -1, b: -1}
        rotations: [0,0,0]
      - !Item
        name: DeathZone
        positions:
        - !Vector3 {x: 20, y: 0, z: 20}
        rotations: [0]
        sizes:
        - !Vector3 {x: 7, y: 0, z: 40}
      - !Item
        name: Ramp
        positions:
        - !Vector3 {x: 3, y: 0, z: 35}
        sizes:
        - !Vector3 {x: 2, y: 0.1, z: 1}
        colors:
        - !RGB {r: 255, g: 0, b: 255}
        rotations: [90]
      - !Item
        name: GoodGoalMultiBounce
        positions:
        - !Vector3 {x: 38.5, y: 0, z: 35}
        rotations: [270]
        sizes:
        - !Vector3 {x: 2, y: 2, z: 2} #Goal Size






