!ArenaConfig
arenas:
  -1: !Arena
    pass_mark: 2
    t: 750
    items:
      - !Item
        name: Agent
        positions:
        - !Vector3 {x: 19, y: 3, z: 9}
        rotations: [0]
        frozenAgentDelays: [10]
      - !Item
        name: Wall
        positions:
        - !Vector3 {x: 20, y: 0, z: 5}
        - !Vector3 {x: 23.25, y: 0, z: 25}
        - !Vector3 {x: 23.25, y: 10, z: 25}
        - !Vector3 {x: 23.51, y: 0, z: 27}
        sizes:
        - !Vector3 {x: 10, y: 2, z: 10}
        - !Vector3 {x: 8, y: 10, z: 2}
        - !Vector3 {x: 8, y: 10, z: 2}
        - !Vector3 {x: 0.02, y: 2, z: 2}
        colors:
        - !RGB {r: 0, g: 0, b: 255}
        - !RGB {r: 1, g: 1, b: 153}
        - !RGB {r: 1, g: 1, b: 153}
        - !RGB {r: 1, g: 1, b: 153}
        rotations: [0,0,0,0]
      - !Item
        name: DeathZone
        positions:
        - !Vector3 {x: 20, y: 0, z: 20}
        rotations: [0]
        sizes:
        - !Vector3 {x: 2, y: 0, z: 40}
      - !Item
        name: Ramp
        positions:
        - !Vector3 {x: 20, y: 0, z: 17}
        - !Vector3 {x: 2, y: 0, z: 38}
        - !Vector3 {x: 25.5, y: 0, z: 27}
        - !Vector3 {x: 24, y: 0, z: 38}
        sizes:
        - !Vector3 {x: 2, y: 1, z: 4}
        - !Vector3 {x: 1, y: 0.01, z: 2}
        - !Vector3 {x: 2, y: 0.6, z: 1}
        - !Vector3 {x: 2, y: 0.8, z: 6}
        colors:
        - !RGB {r: 255, g: 0, b: 255}
        - !RGB {r: 255, g: 0, b: 255}
        - !RGB {r: 255, g: 0, b: 255}
        - !RGB {r: 255, g: 0, b: 255}
        rotations: [90, 90, 90, 270]
      - !Item
        name: GoodGoalMultiBounce
        positions:
        - !Vector3 {x: 39, y: 0, z: 26.5}
        rotations: [270]
        sizes:
        - !Vector3 {x: 1, y: 1, z: 1}
      - !Item
        name: GoodGoal
        positions:
        - !Vector3 {x: 2, y: 0, z: 20}
        sizes:
        - !Vector3 {x: 1, y: 1, z: 1}
      - !Item
        name: GoodGoalMulti
        positions:
        - !Vector3 {x: 26.9, y: 1, z: 38}
        sizes:
        - !Vector3 {x: 1, y: 1, z: 1}
