!ArenaConfig
arenas:
  -1: !Arena
    pass_mark: 2
    t: 500
    items:
      - !Item
        name: Wall
        positions:
        - !Vector3 {x: 20, y: 0, z: 5}
        sizes:
        - !Vector3 {x: 10, y: 2, z: 10}
        colors:
        - !RGB {r: 0, g: 0, b: 255}
        rotations: [0]
      - !Item
        name: Agent
        positions:
        - !Vector3 {x: 20, y: 3, z: 9}
        rotations: [0]
      - !Item
        name: DeathZone
        positions:
        - !Vector3 {x: 20, y: 0, z: 20}
        rotations: [0]
        sizes:
        - !Vector3 {x: 2, y: 0, z: 40}
      - !Item #ramp
        name: Ramp #ramp
        positions: #ramp
        - !Vector3 {x: 20, y: 0, z: 15} #ramp
        sizes: #ramp
        - !Vector3 {x: 2, y: 1, z: 4} #ramp
        colors: #ramp
        - !RGB {r: 255, g: 0, b: 255} #ramp
        rotations: [270] #ramp
      - !Item #GoodGoalBounce 1
        name: GoodGoalBounce #GoodGoalBounce 1
        positions: #GoodGoalBounce 1
        - !Vector3 {x: 38.5, y: 0, z: 25} #GoodGoalBounce 1
        rotations: [270] #GoodGoalBounce 1
        sizes: #GoodGoalBounce 1
        - !Vector3 {x: 1, y: 1, z: 1} #GoodGoalBounce Size
      - !Item #GoodGoalMulti 1
        name: GoodGoalMultiBounce #GoodGoalMultiBounce 1
        positions: #GoodGoalMultiBounce 1
        - !Vector3 {x: 1.5, y: 0, z: 20} #GoodGoalMultiBounce 1
        rotations: [90] #GoodGoalMultiBounce 1
        sizes: #GoodGoalMultiBounce 1
        - !Vector3 {x: 1, y: 1, z: 1} #GoodGoalMultiBounce 1
      - !Item #GoodGoalMultiBounce 2
        name: GoodGoalMultiBounce #GoodGoalMultiBounce 2
        positions: #GoodGoalMultiBounce 2
        - !Vector3 {x: 1.5, y: 0, z: 30} #GoodGoalMultiBounce 2
        rotations: [90] #GoodGoalMultiBounce 2
        sizes: #GoodGoalMultiBounce 2
        - !Vector3 {x: 1, y: 1, z: 1} #GoodGoalMultiBounce 2
