!ArenaConfig
arenas:
  -1: !Arena
    t: 500
    pass_mark: 0
    items:
      - !Item
        name: Agent
        positions:
        - !Vector3 {x: 20, y: 0, z: 15}
        rotations: [-1] #Agent Rotation Parameter
      - !Item
        name: CylinderTunnel
        positions:
        - !Vector3 {x: 20, y: 0, z: 25}
        - !Vector3 {x: 27.5, y: 0, z: 22.99}
        - !Vector3 {x: 12.5, y: 0, z: 22.99}
        sizes:
        - !Vector3 {x: 5, y: 10, z: 4}
        - !Vector3 {x: 5, y: 10, z: 4}
        - !Vector3 {x: 5, y: 10, z: 4}
        colors:
        - !RGB {r: 248, g: 253, b: 212} #color parameter
        - !RGB {r: 248, g: 253, b: 212} #color parameter
        - !RGB {r: 248, g: 253, b: 212} #color parameter
        rotations: [0, 60, 300]
      - !Item
        name: GoodGoal
        positions:
        - !Vector3 {x: 27.5, y: 0, z: 22.5}
        sizes:
        - !Vector3 {x: 1, y: 1, z: 1}
      - !Item
        name: BadGoal
        positions:
        - !Vector3 {x: 20, y: 0, z: 25.5}
        sizes:
        - !Vector3 {x: 1, y: 1, z: 1}
