!ArenaConfig
arenas:
  -1: !Arena
    pass_mark: -0.5
    t: 250
    items:
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 20, y: 0, z: 30}
      - !Vector3 {x: 39.5, y: 0, z: 19.75}
      - !Vector3 {x: 37.5, y: 0, z: 19.75}
      - !Vector3 {x: 35.5, y: 0, z: 19.75}
      - !Vector3 {x: 33.5, y: 0, z: 19.75}
      - !Vector3 {x: 31.5, y: 0, z: 19.75}
      - !Vector3 {x: 29.5, y: 0, z: 19.75}
      - !Vector3 {x: 27.5, y: 0, z: 19.75}
      - !Vector3 {x: 25.5, y: 0, z: 19.75}
      - !Vector3 {x: 23.5, y: 0, z: 19.75}
      - !Vector3 {x: 21.5, y: 0, z: 19.75}
      - !Vector3 {x: 19.5, y: 0, z: 19.75}
      - !Vector3 {x: 17.5, y: 0, z: 19.75}
      - !Vector3 {x: 15.5, y: 0, z: 19.75}
      - !Vector3 {x: 13.5, y: 0, z: 19.75}
      - !Vector3 {x: 9.5, y: 0, z: 19.75}
      rotations: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
      sizes:
      - !Vector3 {x: 40, y: 0.5, z: 20}
      - !Vector3 {x: 1, y: 3, z: 0.5}
      - !Vector3 {x: 1, y: 3, z: 0.5}
      - !Vector3 {x: 1, y: 3, z: 0.5}
      - !Vector3 {x: 1, y: 3, z: 0.5}
      - !Vector3 {x: 1, y: 3, z: 0.5}
      - !Vector3 {x: 1, y: 3, z: 0.5}
      - !Vector3 {x: 1, y: 3, z: 0.5}
      - !Vector3 {x: 1, y: 3, z: 0.5}
      - !Vector3 {x: 1, y: 3, z: 0.5}
      - !Vector3 {x: 1, y: 3, z: 0.5}
      - !Vector3 {x: 1, y: 3, z: 0.5}
      - !Vector3 {x: 1, y: 3, z: 0.5}
      - !Vector3 {x: 1, y: 3, z: 0.5}
      - !Vector3 {x: 1, y: 3, z: 0.5}
      - !Vector3 {x: 5, y: 3, z: 0.5}
      colors:
      - !RGB {r: 0, g: 0, b: 255}
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
      - !RGB {r: 1, g: 1, b: 153} #color parameter
    - !Item
      name: Ramp
      positions:
      - !Vector3 {x: 5, y: 0, z: 18}
      sizes:
      - !Vector3 {x: 4, y: 0.5, z: 4}
      rotations: [180]
      colors:
      - !RGB {r: 255, g: 0, b: 255}
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 20, y: 0.5, z: 35}
      sizes:
      - !Vector3 {x: 0.5, y: 0.5, z: 0.5} #Goal Size
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 35, y: 0, z: 5}
      rotations: [135] #Agent Rotation Parameter
