!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 3
    t: 400
    items:
      - !Item
        name: Agent
        positions:
        - !Vector3 {x: 20, y: 2, z: 1}
        rotations: [0]
        frozenAgentDelays: [8]
      - !Item
        name: Wall
        positions:
        - !Vector3 {x: 20, y: 0, z: 5}
        - !Vector3 {x: 22.5, y: 0, z: 10.1}
        - !Vector3 {x: 34, y: 0, z: 10.1}
        - !Vector3 {x: 27.75, y: 0, z: 10.1}
        - !Vector3 {x: 28.75, y: 1.25, z: 10.1}
        - !Vector3 {x: 31.5, y: 0, z: 12.5}
        - !Vector3 {x: 20, y: 0.7, z: 7.5}
        sizes:
        - !Vector3 {x: 2, y: 0.7, z: 10}
        - !Vector3 {x: 10, y: 1.25, z: 0.05}
        - !Vector3 {x: 12, y: 1.25, z: 0.05}
        - !Vector3 {x: 0.5, y: 0.5, z: 0.05}
        - !Vector3 {x: 22.5, y: 3, z: 0.05}
        - !Vector3 {x: 1, y: 2.5, z: 4}
        - !Vector3 {x: 2, y: 2.3, z: 5}
        colors:
        - !RGB {r: 0, g: 0, b: 255}
        - !RGB {r: 1, g: 100, b: 1}
        - !RGB {r: 1, g: 100, b: 1}
        - !RGB {r: 1, g: 100, b: 1}
        - !RGB {r: 1, g: 100, b: 1}
        - !RGB {r: 0, g: 0, b: 255}
        - !RGB {r: 0, g: 0, b: 255}
        rotations: [0, 0, 0, 0, 0, 0, 0]
      - !Item
        name: Ramp
        positions:
        - !Vector3 {x: 25.5, y: 0, z: 12.5}
        sizes:
        - !Vector3 {x: 4, y: 1.5, z: 4}
        rotations: [270]
        colors:
        - !RGB {r: 255, g: 0, b: 255}
      - !Item
        name: GoodGoalBounce
        positions:
        - !Vector3 {x: 2, y: 1, z: 12}
        sizes:
        - !Vector3 {x: 3, y: 3, z: 3}
        rotations: [90]
      - !Item #decoy
        name: GoodGoal #decoy
        positions: #decoy
        - !Vector3 {x: 29, y: 0.5, z: 5} #decoy position
        sizes: #decoy
        - !Vector3 {x: 4, y: 4, z: 4} #decoy size
        rotations: [0] #decoy
