!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2
    t: 350
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 3, z: 5}
      rotations: [180] #Agent Rotation
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 5.5, y: 1, z: 17}
      sizes:
      - !Vector3 {x: 3, y: 3, z: 3} #Goal Size
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 20, y: 0, z: 20} #centre base.
      - !Vector3 {x: 20, y: 0, z: 5.25} #bottom arm end.
      - !Vector3 {x: 20, y: 0, z: 11} #bottom arm.
      - !Vector3 {x: 29, y: 0, z: 20} #right arm.
      - !Vector3 {x: 34.75, y: 0, z: 18.75} #right arm end.
      - !Vector3 {x: 11, y: 0, z: 20} #left arm.
      - !Vector3 {x: 5.25, y: 0, z: 18.75} #left arm end.
      rotations: [0, 0, 0, 0, 0, 0, 0]
      sizes:
      - !Vector3 {x: 9, y: .2, z: 9} #centre base.
      - !Vector3 {x: 5, y: .2, z: 2.5} #botom arm end.
      - !Vector3 {x: 2.5, y: .2, z: 9} #bottom arm.
      - !Vector3 {x: 9, y: .2, z: 2.5} #right arm.
      - !Vector3 {x: 2.5, y: .2, z: 5} #right arm end.
      - !Vector3 {x: 9, y: .2, z: 2.5} #left arm.
      - !Vector3 {x: 2.5, y: .2, z: 5} #left arm end.
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: DeathZone
      positions:
      - !Vector3 {x: 20, y: 0, z: 20}
      rotations: [0]
      sizes:
      - !Vector3 {x: 40, y: 0, z: 40}
