!ArenaConfig
arenas:
  -1: !Arena
    pass_mark: 1.5
    t: 500
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 1, y: 0, z: 1}
      rotations: [-1] #Agent Rotation Parameter
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 2, y: 0, z: 25}
      - !Vector3 {x: 20, y: 0, z: 39}
      - !Vector3 {x: 38, y: 0, z: 25}
      - !Vector3 {x: 20, y: 0, z: 20}
      rotations: [0,0,0,0]
      colors:
      - !RGB {r: 0, g: 0, b: 255}
      - !RGB {r: 0, g: 0, b: 255}
      - !RGB {r: 0, g: 0, b: 255}
      - !RGB {r: 153, g: 153, b: 153} #color parameter
      sizes:
      - !Vector3 {x: 4, y: 1, z: 30}
      - !Vector3 {x: 32, y: 1, z: 2}
      - !Vector3 {x: 4, y: 1, z: 30}
      - !Vector3 {x: 2, y: 4, z: 22}
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 2, y: 1, z: 12}
      sizes:
      - !Vector3 {x: 2.5, y: 2.5, z: 2.5} #Goal Size
    - !Item
      name: Ramp
      positions:
      - !Vector3 {x: 38, y: 0, z: 7.5}
      rotations: [180]
      sizes:
      - !Vector3 {x: 4, y: 1, z: 5}
      colors:
      - !RGB {r: 255, g: 0, b: 255}
