!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2.5 #pass mark
    t: 750 #time limit
    items:
      - !Item
        name: Agent
        positions:
        - !Vector3 {x: 19, y: 3, z: 9} #agent position
        rotations: [0]
        frozenAgentDelays: [10]
      - !Item #walls
        name: Wall #walls
        positions: #walls
        - !Vector3 {x: 20, y: 0, z: 5} #walls
        - !Vector3 {x: 23.25, y: 0, z: 25} #walls
        - !Vector3 {x: 23.25, y: 10, z: 25} #walls
        - !Vector3 {x: 23.25, y: 20, z: 25} #walls
        - !Vector3 {x: 23.51, y: 0, z: 28} #walls
        sizes: #walls
        - !Vector3 {x: 10, y: 2, z: 10} #walls
        - !Vector3 {x: 8, y: 10, z: 2} #walls
        - !Vector3 {x: 8, y: 10, z: 2} #walls
        - !Vector3 {x: 8, y: 10, z: 2} #walls
        - !Vector3 {x: 0.02, y: 2, z: 4} #walls
        colors: #walls
        - !RGB {r: 0, g: 0, b: 255} #walls
        - !RGB {r: 1, g: 100, b: 1} #walls
        - !RGB {r: 1, g: 100, b: 1} #walls
        - !RGB {r: 1, g: 100, b: 1} #walls
        - !RGB {r: 1, g: 100, b: 1} #walls
        rotations: [0,0,0,0,0] #walls
      - !Item #deathzone
        name: DeathZone #deathzone
        positions: #deathzone
        - !Vector3 {x: 20, y: 0, z: 20} #deathzone
        rotations: [0] #deathzone
        sizes: #deathzone
        - !Vector3 {x: 2, y: 0, z: 40} #deathzone
      - !Item #ramps
        name: Ramp #ramps
        positions: #ramps
        - !Vector3 {x: 20, y: 0, z: 17} #ramps
        - !Vector3 {x: 25.5, y: 0, z: 28} #ramps
        - !Vector3 {x: 21.25, y: 0, z: 28} #ramps
        sizes:
        - !Vector3 {x: 2, y: 1, z: 4} #ramps
        - !Vector3 {x: 2, y: 0.6, z: 1} #ramps
        - !Vector3 {x: 2, y: 0.5, z: 4} #ramps
        colors:
        - !RGB {r: 255, g: 0, b: 255} #ramps
        - !RGB {r: 255, g: 0, b: 255} #ramps
        - !RGB {r: 255, g: 0, b: 255} #ramps
        rotations: [90, 90, 270] #ramps
      - !Item #initial goodgoal pre-explosion
        name: GoodGoalMultiBounce #initial goodgoal pre-explosion
        positions: #initial goodgoal pre-explosion
        - !Vector3 {x: 39, y: 0, z: 28} #initial goodgoal pre-explosion
        rotations: [270] #initial goodgoal pre-explosion
        sizes: #initial goodgoal pre-explosion
        - !Vector3 {x: 1, y: 1, z: 1} #initial goodgoal pre-explosion
      - !Item #Extra GoodGoal
        name: GoodGoal #Extra GoodGoal
        positions: #Extra GoodGoal
        - !Vector3 {x: 2, y: 0, z: 20} #Extra GoodGoal
        sizes: #Extra GoodGoal
        - !Vector3 {x: 1, y: 1, z: 1} #Extra GoodGoal
      - !Item #Explosion GoodGoalMulti
        name: GoodGoalMulti #Explosion GoodGoalMulti
        positions: #Explosion GoodGoalMulti
        - !Vector3 {x: 18.5, y: 18, z: 28} #Explosion GoodGoalMulti
        sizes: #Explosion GoodGoalMulti
        - !Vector3 {x: 1.5, y: 1.5, z: 1.5} #Explosion GoodGoalMulti
