!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0
    t: 500
    items:
      - !Item
        name: Wall
        positions:
        - !Vector3 {x: 20, y: 0, z: 5}
        sizes:
        - !Vector3 {x: 10, y: 2, z: 10}
        colors:
        - !RGB {r: 0, g: 0, b: 255}
        rotations: [0]
      - !Item
        name: Agent
        positions:
        - !Vector3 {x: 20, y: 3, z: 9}
        rotations: [0]
      - !Item
        name: DeathZone
        positions:
        - !Vector3 {x: 20, y: 0, z: 20}
        rotations: [0]
        sizes:
        - !Vector3 {x: 2, y: 0, z: 40}
      - !Item #ramp
        name: Ramp #ramp
        positions: #ramp
        - !Vector3 {x: 20, y: 0, z: 15} #ramp
        sizes: #ramp
        - !Vector3 {x: 2, y: 1, z: 4} #ramp
        colors: #ramp
        - !RGB {r: 255, g: 0, b: 255} #ramp
        rotations: [270] #ramp
      - !Item #GoodGoal
        name: GoodGoal #GoodGoal
        positions: #GoodGoal
        - !Vector3 {x: 1.5, y: 0, z: 22} #GoodGoal
        rotations: [90] #GoodGoal
        sizes: #GoodGoal
        - !Vector3 {x: 1, y: 1, z: 1} #GoodGoal Size
      - !Item #GoodGoalMulti
        name: GoodGoalMulti #GoodGoalMulti
        positions: #GoodGoalMulti
        - !Vector3 {x: 38.5, y: 0, z: 28} #GoodGoalMulti
        rotations: [270] #GoodGoalMulti
        sizes: #GoodGoalMulti
        - !Vector3 {x: 1, y: 1, z: 1} #GoodGoalMulti
