!ArenaConfig
arenas:
  -1: !Arena
    pass_mark: 1
    t: 250
    items:
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 20, y: 0, z: 30}
      - !Vector3 {x: 15, y: 0, z: 19}
      rotations: [0, 0]
      sizes:
      - !Vector3 {x: 40, y: 0.5, z: 20}
      - !Vector3 {x: 16, y: 3, z: 2}
      colors:
      - !RGB {r: 0, g: 0, b: 255}
      - !RGB {r: 1, g: 1, b: 153} #color parameter
    - !Item
      name: Ramp
      positions:
      - !Vector3 {x: 5, y: 0, z: 18}
      sizes:
      - !Vector3 {x: 4, y: 0.5, z: 4}
      rotations: [180]
      colors:
      - !RGB {r: 255, g: 0, b: 255}
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 20, y: 0.5, z: 35}
      sizes:
      - !Vector3 {x: 2, y: 2, z: 2} #Goal Size
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 35, y: 0, z: 5}
      rotations: [315] #Agent Rotation Parameter
