!ArenaConfig
arenas:
  -1: !Arena
    pass_mark: 2
    t: 750
    items:
      - !Item
        name: Agent
        positions:
        - !Vector3 {x: 21, y: 3, z: 9}
        rotations: [0]
        frozenAgentDelays: [15]
      - !Item
        name: Wall
        positions:
        - !Vector3 {x: 20, y: 0, z: 5}
        - !Vector3 {x: 16.75, y: 0, z: 17.5}
        - !Vector3 {x: 16.75, y: 10, z: 17.5}
        - !Vector3 {x: 16.49, y: 0, z: 19.5}
        sizes:
        - !Vector3 {x: 10, y: 2, z: 10}
        - !Vector3 {x: 8, y: 10, z: 2}
        - !Vector3 {x: 8, y: 10, z: 2}
        - !Vector3 {x: 0.02, y: 2, z: 2}
        colors:
        - !RGB {r: 0, g: 0, b: 255}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        - !RGB {r: 236, g: 195, b: 153}
        rotations: [0,0,0,0]
      - !Item
        name: DeathZone
        positions:
        - !Vector3 {x: 20, y: 0, z: 20}
        rotations: [0]
        sizes:
        - !Vector3 {x: 2, y: 0, z: 40}
      - !Item
        name: Ramp
        positions:
        - !Vector3 {x: 20, y: 0, z: 14}
        - !Vector3 {x: 38, y: 0, z: 19}
        - !Vector3 {x: 14.5, y: 0, z: 19.5}
        - !Vector3 {x: 18.75, y: 0, z: 19.5}
        sizes:
        - !Vector3 {x: 2, y: 1, z: 4}
        - !Vector3 {x: 1, y: 0.01, z: 2}
        - !Vector3 {x: 2, y: 0.6, z: 1}
        - !Vector3 {x: 2, y: 0.0005, z: 4}
        colors:
        - !RGB {r: 255, g: 0, b: 255}
        - !RGB {r: 255, g: 0, b: 255}
        - !RGB {r: 255, g: 0, b: 255}
        - !RGB {r: 255, g: 0, b: 255}
        rotations: [270, 270, 270, 90]
      - !Item
        name: GoodGoalMultiBounce
        positions:
        - !Vector3 {x: 1, y: 0, z: 19}
        rotations: [90]
        sizes:
        - !Vector3 {x: 1, y: 1, z: 1}
      - !Item
        name: GoodGoal
        positions:
        - !Vector3 {x: 38, y: 0, z: 26.75}
        sizes:
        - !Vector3 {x: 1, y: 1, z: 1}
      - !Item
        name: GoodGoalMulti
        positions:
        - !Vector3 {x: 17.8, y: 18, z: 19.25}
        sizes:
        - !Vector3 {x: 1, y: 1, z: 1}
