!ArenaConfig
arenas:
  0: !Arena
    t: 500
    items:
      - !Item
        name: Agent
        positions:
        - !Vector3 {x: 20, y: 0, z: 15}
        rotations: [-1] #Agent Rotation Parameter
      - !Item
        name: CylinderTunnel
        positions:
        - !Vector3 {x: 20, y: 0, z: 25}
        - !Vector3 {x: 27.5, y: 0, z: 22.99}
        - !Vector3 {x: 12.5, y: 0, z: 22.99}
        sizes:
        - !Vector3 {x: 5, y: 10, z: 4}
        - !Vector3 {x: 5, y: 10, z: 4}
        - !Vector3 {x: 5, y: 10, z: 4}
        colors:
        - !RGB {r: 236, g: 195, b: 153} #color parameter
        - !RGB {r: 236, g: 195, b: 153} #color parameter
        - !RGB {r: 236, g: 195, b: 153} #color parameter
        rotations: [0, 60, 300]
      - !Item
        name: Wall
        positions:
        - !Vector3 {x: 18, y: 0, z: 30}#centre left wall.
        - !Vector3 {x: 22, y: 0, z: 30}#centre right wall.
        - !Vector3 {x: 19.1875, y: 0, z: 32.75} #centre left occluder.
        - !Vector3 {x: 20.8125, y: 0, z: 29.825} #centre right occluder.
        - !Vector3 {x: 30.8, y: 0, z: 27.3} #right left wall.
        - !Vector3 {x: 33, y: 0, z: 23.825} #right right wall.
        - !Vector3 {x: 33.7, y: 0, z: 27.6} #right left occluder.
        - !Vector3 {x: 32.125, y: 0, z: 24.7} #right right occluder.
        - !Vector3 {x: 7, y: 0, z: 23.825} #left left wall.
        - !Vector3 {x: 9.2, y: 0, z: 27.3} #left right wall.
        - !Vector3 {x: 5.25, y: 0, z: 26.2} #left left occluder.
        - !Vector3 {x: 8.625, y: 0, z: 26.2} #left right occluder.
        rotations: [0,0,0,0,60,60,60,60,300,300,300,300]
        sizes:
        - !Vector3 {x: .5, y: 5, z: 6} #centre left wall.
        - !Vector3 {x: .5, y: 5, z: 6} #centre right wall.
        - !Vector3 {x: 1.825, y: 5, z: .5} #centre left occluder.
        - !Vector3 {x: 1.825, y: 5, z: .5} #centre right occluder.
        - !Vector3 {x: .5, y: 5, z: 6} #right left wall.
        - !Vector3 {x: .5, y: 5, z: 6} #right right wall.
        - !Vector3 {x: 1.825, y: 5, z: .5} #right left occluder.
        - !Vector3 {x: 1.825, y: 5, z: .5} #right right occluder.
        - !Vector3 {x: .5, y: 5, z: 6} #left left wall.
        - !Vector3 {x: .5, y: 5, z: 6} #left right wall.
        - !Vector3 {x: 1.825, y: 5, z: .5} #left left occluder.
        - !Vector3 {x: 1.825, y: 5, z: .5} #left right occluder.
        colors:
        - !RGB {r: 236, g: 195, b: 153} #color parameter
        - !RGB {r: 236, g: 195, b: 153} #color parameter
        - !RGB {r: 236, g: 195, b: 153} #color parameter
        - !RGB {r: 236, g: 195, b: 153} #color parameter
        - !RGB {r: 236, g: 195, b: 153} #color parameter
        - !RGB {r: 236, g: 195, b: 153} #color parameter
        - !RGB {r: 236, g: 195, b: 153} #color parameter
        - !RGB {r: 236, g: 195, b: 153} #color parameter
        - !RGB {r: 236, g: 195, b: 153} #color parameter
        - !RGB {r: 236, g: 195, b: 153} #color parameter
        - !RGB {r: 236, g: 195, b: 153} #color parameter
        - !RGB {r: 236, g: 195, b: 153} #color parameter
      - !Item
        name: WallTransparent
        positions:
        - !Vector3 {x: 20, y: 0, z: 22.75}
        - !Vector3 {x: 25.25, y: 0, z: 21.625}
        - !Vector3 {x: 14.75, y: 0, z: 21.625}
        sizes:
        - !Vector3 {x: 4, y: 3.5, z: .2}
        - !Vector3 {x: 4, y: 3.5, z: .2}
        - !Vector3 {x: 4, y: 3.5, z: .2}
        rotations: [0, 60, 300]
      - !Item
        name: Ramp
        positions:
        - !Vector3 {x: 20.9, y: 0, z: 32.75} #centre.
        - !Vector3 {x: 34.625, y: 0, z: 25.99} #right.
        - !Vector3 {x: 6.1, y: 0, z: 27.8} #left.
        rotations: [0,60,300]
        sizes:
        - !Vector3 {x: 1.5, y: .5, z: .5} #centre.
        - !Vector3 {x: 1.5, y: .5, z: .5} #right.
        - !Vector3 {x: 1.5, y: .5, z: .5} #left.
        colors:
        - !RGB {r: 255, g: 0, b: 255}
        - !RGB {r: 255, g: 0, b: 255}
        - !RGB {r: 255, g: 0, b: 255}
      - !Item
        name: GoodGoal
        positions:
        - !Vector3 {x: 12.5, y: 0, z: 23.5}
        sizes:
        - !Vector3 {x: 0.5, y: 0.5, z: 0.5} #Goal Size
      - !Item
        name: BadGoal
        positions:
        - !Vector3 {x: 27.5, y: 0, z: 22.5}
        sizes:
        - !Vector3 {x: 0.5, y: 0.5, z: 0.5} #Goal Size

    pass_mark: -0.5

