!ArenaConfig
arenas:
  -1: !Arena
    pass_mark: 0
    t: 250
    items:
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 20, y: 0, z: 30}
      - !Vector3 {x: 0.5, y: 0, z: 19.75}
      - !Vector3 {x: 2.5, y: 0, z: 19.75}
      - !Vector3 {x: 4.5, y: 0, z: 19.75}
      - !Vector3 {x: 6.5, y: 0, z: 19.75}
      - !Vector3 {x: 8.5, y: 0, z: 19.75}
      - !Vector3 {x: 10.5, y: 0, z: 19.75}
      - !Vector3 {x: 12.5, y: 0, z: 19.75}
      - !Vector3 {x: 14.5, y: 0, z: 19.75}
      - !Vector3 {x: 16.5, y: 0, z: 19.75}
      - !Vector3 {x: 18.5, y: 0, z: 19.75}
      - !Vector3 {x: 20.5, y: 0, z: 19.75}
      - !Vector3 {x: 22.5, y: 0, z: 19.75}
      - !Vector3 {x: 24.5, y: 0, z: 19.75}
      - !Vector3 {x: 26.5, y: 0, z: 19.75}
      - !Vector3 {x: 30.5, y: 0, z: 19.75}
      rotations: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
      sizes:
      - !Vector3 {x: 40, y: 0.5, z: 20}
      - !Vector3 {x: 1, y: 3, z: 0.5}
      - !Vector3 {x: 1, y: 3, z: 0.5}
      - !Vector3 {x: 1, y: 3, z: 0.5}
      - !Vector3 {x: 1, y: 3, z: 0.5}
      - !Vector3 {x: 1, y: 3, z: 0.5}
      - !Vector3 {x: 1, y: 3, z: 0.5}
      - !Vector3 {x: 1, y: 3, z: 0.5}
      - !Vector3 {x: 1, y: 3, z: 0.5}
      - !Vector3 {x: 1, y: 3, z: 0.5}
      - !Vector3 {x: 1, y: 3, z: 0.5}
      - !Vector3 {x: 1, y: 3, z: 0.5}
      - !Vector3 {x: 1, y: 3, z: 0.5}
      - !Vector3 {x: 1, y: 3, z: 0.5}
      - !Vector3 {x: 1, y: 3, z: 0.5}
      - !Vector3 {x: 5, y: 3, z: 0.5}
      colors:
      - !RGB {r: 0, g: 0, b: 255}
      - !RGB {r: 1, g: 100, b: 1} #color parameter
      - !RGB {r: 1, g: 100, b: 1} #color parameter
      - !RGB {r: 1, g: 100, b: 1} #color parameter
      - !RGB {r: 1, g: 100, b: 1} #color parameter
      - !RGB {r: 1, g: 100, b: 1} #color parameter
      - !RGB {r: 1, g: 100, b: 1} #color parameter
      - !RGB {r: 1, g: 100, b: 1} #color parameter
      - !RGB {r: 1, g: 100, b: 1} #color parameter
      - !RGB {r: 1, g: 100, b: 1} #color parameter
      - !RGB {r: 1, g: 100, b: 1} #color parameter
      - !RGB {r: 1, g: 100, b: 1} #color parameter
      - !RGB {r: 1, g: 100, b: 1} #color parameter
      - !RGB {r: 1, g: 100, b: 1} #color parameter
      - !RGB {r: 1, g: 100, b: 1} #color parameter
      - !RGB {r: 1, g: 100, b: 1} #color parameter
    - !Item
      name: Ramp
      positions:
      - !Vector3 {x: 35, y: 0, z: 18}
      sizes:
      - !Vector3 {x: 4, y: 0.5, z: 4}
      rotations: [180]
      colors:
      - !RGB {r: 255, g: 0, b: 255}
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 20, y: 0.5, z: 35}
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1} #Goal Size
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 5, y: 0, z: 5}
      rotations: [45] #Agent Rotation Parameter
