!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0
    t: 500
    items:
    - !Item
      name: WallTransparent
      positions:
      - !Vector3 {x: 15, y: 0, z: 25}
      - !Vector3 {x: 25, y: 0, z: 25}
      - !Vector3 {x: 15, y: 0, z: 15}
      - !Vector3 {x: 25, y: 0, z: 15}
      rotations: [45, 135, 135, 45]
      sizes:
      - !Vector3 {x: 13, y: 10, z: 1}
      - !Vector3 {x: 13, y: 10, z: 1}
      - !Vector3 {x: 13, y: 10, z: 1}
      - !Vector3 {x: 13, y: 10, z: 1}
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 15, y: 0, z: 24.2}
      - !Vector3 {x: 25, y: 0, z: 24.2}
      - !Vector3 {x: 15, y: 0, z: 14.2}
      - !Vector3 {x: 25, y: 0, z: 14.2}
      rotations: [45, 135, 135, 45]
      sizes:
      - !Vector3 {x: 4, y: 10, z: 0.001}
      - !Vector3 {x: 4, y: 10, z: 0.001}
      - !Vector3 {x: 4, y: 10, z: 0.001}
      - !Vector3 {x: 4, y: 10, z: 0.001}
      colors:
      - !RGB {r: -1, g: -1, b: -1} #color parameter
      - !RGB {r: -1, g: -1, b: -1} #color parameter
      - !RGB {r: -1, g: -1, b: -1} #color parameter
      - !RGB {r: -1, g: -1, b: -1} #color parameter
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 16, y: 0, z: 20}
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1} #Goal Size
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 18}
      rotations: [0] #Agent Rotation Parameter
      skins:
      - "hedgehog"
