!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0.5
    t: 350
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 16.5, y: 1, z: 6.5}
      rotations: [-1] #Agent Rotation
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 5.5, y: 1, z: 10}
      sizes:
      - !Vector3 {x: 1.5, y: 1.5, z: 1.5} #Goal Size
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 20, y: 0, z: 20} #centre base.
      - !Vector3 {x: 26.5, y: 0, z: 34.75} #top right arm end.
      - !Vector3 {x: 23.25, y: 0, z: 29} #top right arm.
      - !Vector3 {x: 13.5, y: 0, z: 34.75} #top left arm end.
      - !Vector3 {x: 16.75, y: 0, z: 29} #top left arm.
      - !Vector3 {x: 26.5, y: 0, z: 5.25} #bottom right arm end.
      - !Vector3 {x: 23.25, y: 0, z: 11} #bottom right arm.
      - !Vector3 {x: 13.5, y: 0, z: 5.25} #bottom  left arm end.
      - !Vector3 {x: 16.75, y: 0, z: 11} #bottom  left arm.
      - !Vector3 {x: 29, y: 0, z: 22.5} #upper right arm.
      - !Vector3 {x: 34.75, y: 0, z: 25.75} #upper right arm end.
      - !Vector3 {x: 29, y: 0, z: 17.5} #path to lower right arm.
      - !Vector3 {x: 34.75, y: 0, z: 14.25} #lower right arm end.
      - !Vector3 {x: 11, y: 0, z: 22.5} #path to upper left arm.
      - !Vector3 {x: 5.25, y: 0, z: 25.75} #upper left arm end.
      - !Vector3 {x: 11, y: 0, z: 17.5} #path to lower left arm.
      - !Vector3 {x: 5.25, y: 0, z: 14.25} #lower left arm end.
      rotations: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
      sizes:
      - !Vector3 {x: 9, y: .2, z: 9} #centre base.
      - !Vector3 {x: 9, y: .2, z: 2.5} #top right arm end.
      - !Vector3 {x: 2.5, y: .2, z: 9} #top right arm.
      - !Vector3 {x: 9, y: .2, z: 2.5} #top left arm end.
      - !Vector3 {x: 2.5, y: .2, z: 9} #top left arm.
      - !Vector3 {x: 9, y: .2, z: 2.5} #bottom right arm end.
      - !Vector3 {x: 2.5, y: .2, z: 9} #bottom right arm.
      - !Vector3 {x: 9, y: .2, z: 2.5} #bottom left arm end.
      - !Vector3 {x: 2.5, y: .2, z: 9} #bottom left arm.
      - !Vector3 {x: 9, y: .2, z: 2.5} #path to upper right arm.
      - !Vector3 {x: 2.5, y: .2, z: 9} #upper right arm end.
      - !Vector3 {x: 9, y: .2, z: 2.5} #path to upper left arm.
      - !Vector3 {x: 2.5, y: .2, z: 9} #upper left arm end.
      - !Vector3 {x: 9, y: .2, z: 2.5} #path to lower right arm.
      - !Vector3 {x: 2.5, y: .2, z: 9} #lower right arm end.
      - !Vector3 {x: 9, y: .2, z: 2.5} #path to lower left arm.
      - !Vector3 {x: 2.5, y: .2, z: 9} #lower left arm end.
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: DeathZone
      positions:
      - !Vector3 {x: 20, y: 0, z: 20}
      rotations: [0]
      sizes:
      - !Vector3 {x: 40, y: 0, z: 40}
