!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2 #decoy
    #pass_mark: 1
    t: 500
    items:
      - !Item
        name: Agent
        positions:
        - !Vector3 {x: 20, y: 3, z: 9}
        rotations: [0]
        frozenAgentDelays: [12]
      - !Item
        name: Wall
        positions:
        - !Vector3 {x: 20, y: 0, z: 5}
        - !Vector3 {x: 15, y: 0.5, z: 25}
        - !Vector3 {x: 25, y: 0.5, z: 25}
        - !Vector3 {x: 20, y: 0, z: 25}
        sizes:
        - !Vector3 {x: 10, y: 2, z: 10}
        - !Vector3 {x: 5.5, y: 11, z: 2}
        - !Vector3 {x: 5.5, y: 11, z: 2}
        - !Vector3 {x: 15.5, y: 0.5, z: 2}
        colors:
        - !RGB {r: 0, g: 0, b: 255}
        - !RGB {r: 248, g: 253, b: 212}
        - !RGB {r: 248, g: 253, b: 212}
        - !RGB {r: 248, g: 253, b: 212}
        rotations: [0,0,0,0]
      - !Item
        name: DeathZone
        positions:
        - !Vector3 {x: 20, y: 0, z: 20}
        rotations: [0]
        sizes:
        - !Vector3 {x: 5, y: 0, z: 40}
      - !Item
        name: Ramp
        positions:
        - !Vector3 {x: 38, y: 0, z: 30}
        sizes:
        - !Vector3 {x: 1, y: 0.1, z: 1}
        colors:
        - !RGB {r: 255, g: 0, b: 255}
        rotations: [270]
      - !Item
        name: GoodGoalMultiBounce
        positions:
        - !Vector3 {x: 1.5, y: 0, z: 30}
        rotations: [90]
        sizes:
        - !Vector3 {x: 2, y: 2, z: 2} #Goal Size
      - !Item #decoy
        name: GoodGoal  #decoy
        positions:  #decoy
        - !Vector3 {x: 39, y: 0, z: 35}  #decoy
        sizes:  #decoy
        - !Vector3 {x: 1, y: 1, z: 1}  #decoy
