!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 1.5
    t: 250
    items:
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 20, y: 0, z: 20}
      - !Vector3 {x: 20, y: 3.1, z: 20}
      - !Vector3 {x: 10.25, y: .1, z: 12}
      - !Vector3 {x: 10.25, y: .1, z: 28}
      - !Vector3 {x: 20, y: .1, z: 10.25}
      - !Vector3 {x: 20, y: .1, z: 29.75}
      rotations: [0,0,0,0,0,0]
      sizes:
      - !Vector3 {x: 20, y: 0.1, z: 20}
      - !Vector3 {x: 20, y: 0.1, z: 20}
      - !Vector3 {x: 0.5, y: 3, z: 4}
      - !Vector3 {x: 0.5, y: 3, z: 4}
      - !Vector3 {x: 19, y: 3, z: 0.5}
      - !Vector3 {x: 19, y: 3, z: 0.5}
      colors:
      - !RGB {r: 248, g: 253, b: 212} #color parameter
      - !RGB {r: 248, g: 253, b: 212} #color parameter
      - !RGB {r: 248, g: 253, b: 212} #color parameter
      - !RGB {r: 248, g: 253, b: 212} #color parameter
      - !RGB {r: 248, g: 253, b: 212} #color parameter
      - !RGB {r: 248, g: 253, b: 212} #color parameter
    - !Item
      name: WallTransparent
      positions:
      - !Vector3 {x: 29.75, y: .1, z: 20}
      rotations: [0]
      sizes:
      - !Vector3 {x: .5, y: 3, z: 20}
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 32, y: 0, z: 20}
      sizes:
      - !Vector3 {x: 2.5, y: 2.5, z: 2.5} #Goal Size
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: .1, z: 20}
      rotations: [90]
