!ArenaConfig
arenas:
  -1: !Arena
    pass_mark: 3 #pass mark
    t: 750 #time limit
    items:
      - !Item #agent item parameter
        name: Agent #agent name
        positions: #agent position parameter
        - !Vector3 {x: 20, y: 2, z: 1} #agent position
        rotations: [0] #agent rotation
        frozenAgentDelays: [7]
      - !Item #wall item parameter
        name: Wall  #wall name
        positions:  #wall position parameter
        - !Vector3 {x: 20, y: 0, z: 10} #wall position
        - !Vector3 {x: 35.5, y: 0.1, z: 21} #wall position
        - !Vector3 {x: 28, y: 0.1, z: 21} #wall position
        - !Vector3 {x: 24, y: 0.1, z: 21} #wall position
        - !Vector3 {x: 20, y: 0.1, z: 21} #wall position
        - !Vector3 {x: 16, y: 0.1, z: 21} #wall position
        - !Vector3 {x: 12, y: 0.1, z: 21} #wall position
        - !Vector3 {x: 8, y: 0.1, z: 21} #wall position
        - !Vector3 {x: 3.5, y: 0.1, z: 21} #wall position
        - !Vector3 {x: 20, y: 0.7, z: 19} #wall position
        sizes: #wall size parameter
        - !Vector3 {x: 2, y: 0.7, z: 20} #wall size
        - !Vector3 {x: 9, y: 4, z: 0.5} #wall size
        - !Vector3 {x: 2, y: 4, z: 0.5} #wall size
        - !Vector3 {x: 2, y: 4, z: 0.5} #wall size
        - !Vector3 {x: 2, y: 4, z: 0.5} #wall size
        - !Vector3 {x: 2, y: 4, z: 0.5} #wall size
        - !Vector3 {x: 2, y: 4, z: 0.5} #wall size
        - !Vector3 {x: 2, y: 4, z: 0.5} #wall size
        - !Vector3 {x: 7, y: 4, z: 0.5} #wall size
        - !Vector3 {x: 2, y: 1, z: 2} #wall size
        colors: #wall color parameter
        - !RGB {r: 0, g: 0, b: 255} #wall color
        - !RGB {r: 248, g: 253, b: 212} #wall color
        - !RGB {r: 248, g: 253, b: 212} #wall color
        - !RGB {r: 248, g: 253, b: 212} #wall color
        - !RGB {r: 248, g: 253, b: 212} #wall color
        - !RGB {r: 248, g: 253, b: 212} #wall color
        - !RGB {r: 248, g: 253, b: 212} #wall color
        - !RGB {r: 248, g: 253, b: 212} #wall color
        - !RGB {r: 248, g: 253, b: 212} #wall color
        - !RGB {r: 0, g: 0, b: 255} #wall color
        rotations: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0] #wall rotations
      - !Item #ramp item parameter
        name: Ramp #ramp name
        positions: #ramp position parameter
        - !Vector3 {x: 7, y: 0, z: 24} #ramp position
        sizes: #ramp size parameter
        - !Vector3 {x: 5, y: 2.1, z: 4} #ramp size
        rotations: [90] #ramp rotation
        colors: #ramp color parameter
        - !RGB {r: 255, g: 0, b: 255} #ramp color
      - !Item #GoodGoalMultiBounce item parameter
        name: GoodGoalMultiBounce #GoodGoalMultiBounce name
        positions: #GoodGoalMultiBounce position parameter
        - !Vector3 {x: 38, y: 1, z: 24} #GoodGoalMultiBounce position
        sizes: #GoodGoalMultiBounce size parameter
        - !Vector3 {x: 3, y: 3, z: 3} #GoodGoalMultiBounce Size
        rotations: [270] #GoodGoalMultiBounce rotation
      - !Item #death zone item parameter
        name: DeathZone #death zone name
        positions: #death zone position parameter
        - !Vector3 {x: 14.5, y: 0, z: 21} #death zone position
        sizes: #death zone size parameter
        - !Vector3 {x: 21, y: 0, z: 3} #death zone size
        rotations: [0] #death zone rotation
