!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 1
    t: 750
    items:
      - !Item
        name: Agent
        positions:
        - !Vector3 {x: 21, y: 3, z: 9}
        rotations: [0]
        frozenAgentDelays: [10]
      - !Item
        name: Wall
        positions:
        - !Vector3 {x: 20, y: 0, z: 5}
        - !Vector3 {x: 16.75, y: 0, z: 17.5}
        - !Vector3 {x: 16.75, y: 10, z: 17.5}
        sizes:
        - !Vector3 {x: 10, y: 2, z: 10}
        - !Vector3 {x: 8, y: 10, z: 2}
        - !Vector3 {x: 8, y: 10, z: 2}
        colors:
        - !RGB {r: 0, g: 0, b: 255}
        - !RGB {r: 248, g: 253, b: 212}
        - !RGB {r: 248, g: 253, b: 212}
        rotations: [0,0,0]
      - !Item
        name: DeathZone
        positions:
        - !Vector3 {x: 20, y: 0, z: 20}
        rotations: [0]
        sizes:
        - !Vector3 {x: 2, y: 0, z: 40}
      - !Item
        name: Ramp
        positions:
        - !Vector3 {x: 20, y: 0, z: 14}
        - !Vector3 {x: 38, y: 0, z: 20}
        sizes:
        - !Vector3 {x: 2, y: 1, z: 4}
        - !Vector3 {x: 1, y: 0.1, z: 2}
        colors:
        - !RGB {r: 255, g: 0, b: 255}
        - !RGB {r: 255, g: 0, b: 255}
        rotations: [270, 270]
      - !Item
        name: GoodGoalMultiBounce
        positions:
        - !Vector3 {x: 1, y: 0, z: 20}
        rotations: [90]
        sizes:
        - !Vector3 {x: 1, y: 1, z: 1}
